# Generated by Django 5.0.1 on 2024-07-17 04:34

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="Restaurant",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("name", models.CharField(max_length=100)),
                ("cuisine", models.CharField(max_length=100)),
                ("city", models.CharField(max_length=100)),
                ("address", models.TextField()),
                ("country_code", models.IntegerField()),
                ("rating", models.FloatField()),
                ("number_of_ratings", models.IntegerField()),
                ("cost_for_two", models.IntegerField()),
            ],
        ),
    ]
