# Generated by Django 5.0.1 on 2024-07-18 06:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("restaurants", "0002_restaurant_image_url"),
    ]

    operations = [
        migrations.AlterField(
            model_name="restaurant",
            name="cuisine",
            field=models.CharField(default="", max_length=100),
        ),
    ]
