# Generated by Django 5.0.1 on 2024-07-18 06:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("restaurants", "0003_alter_restaurant_cuisine"),
    ]

    operations = [
        migrations.AlterField(
            model_name="restaurant",
            name="rating",
            field=models.FloatField(default=0),
        ),
    ]
