# Generated by Django 5.0.1 on 2024-07-18 07:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("restaurants", "0004_alter_restaurant_rating"),
    ]

    operations = [
        migrations.AlterField(
            model_name="restaurant",
            name="cost_for_two",
            field=models.IntegerField(null=True),
        ),
        migrations.AlterField(
            model_name="restaurant",
            name="cuisine",
            field=models.CharField(max_length=100, null=True),
        ),
        migrations.AlterField(
            model_name="restaurant",
            name="number_of_ratings",
            field=models.IntegerField(null=True),
        ),
        migrations.AlterField(
            model_name="restaurant",
            name="rating",
            field=models.FloatField(null=True),
        ),
    ]
