databases:
  - name: ZomatoDB
    plan: free
    databaseName: zomatodb_efux
    user: zomatodb_efux_user

services:
  - type: web
    plan: free
    name: zomato_project
    runtime: python
    buildCommand: "./build.sh"
    startCommand: "python -m gunicorn zomato_project.asgi:application -k uvicorn.workers.UvicornWorker"
    envVars:
      - key: DATABASE_URL
        fromDatabase:
          name: ZomatoDB
          property: connectionString
      - key: SECRET_KEY
        generateValue: true
      - key: WEB_CONCURRENCY
        value: 4